version: "3"
services:
  server:
    image: posh3120/server:prodv1.6
    deploy:
      restart_policy:
        condition: any
    depends_on:
      - postgres
    environment:
      - MAISON_LILA_SHOP_URL=${MAISON_LILA_SHOP_URL}
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - APP_PASSWORD=${APP_PASSWORD}
      - FACEBOOK_PIXEL_URL=${FACEBOOK_PIXEL_URL}
    ports:
      - 8081:8000
    networks:
      - mynetwork

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - mynetwork

  admin:
    image: posh3120/dashboard:prodv1.6
    deploy:
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 15s
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dq2hgf98y
    ports:
      - 8083:3001
    networks:
      - mynetwork

  delivery:
    image: posh3120/delivery:prodv1.4
    deploy:
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 15s
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dq2hgf98y
      - DELIVERY_DATABASE_URL=${DELIVERY_DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXT_PUBLIC_CLOUDINARY_FOLDER_DEV=${NEXT_PUBLIC_CLOUDINARY_FOLDER_DEV}
      - NEXT_PUBLIC_CLOUDINARY_FOLDER_PROD=${NEXT_PUBLIC_CLOUDINARY_FOLDER_PROD}
      - NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=${NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
    ports:
      - 8084:3002
    networks:
      - mynetwork

  store:
    image: posh3120/store:prodv1.6
    deploy:
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 15s
    environment:
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dq2hgf98y
      - NEXT_PUBLIC_PB_PIXEL=${NEXT_PUBLIC_PB_PIXEL}
      - NEXT_PUBLIC_API_KEY =${NEXT_PUBLIC_API_KEY}
      - NEXT_PUBLIC_API_HOST =${NEXT_PUBLIC_API_HOST}
    depends_on:
      - server
      - admin
    ports:
      - 8082:3000
    networks:
      - mynetwork

volumes:
  postgres:
networks:
  mynetwork:
    driver: overlay
