version: "3"
services:
  server:
    image: posh3120/maison_lila_server:v0.1
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 8081:8000

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  admin:
    image: posh3120/maison_lila_dashboard:v0.1
    depends_on:
      - server
    ports:
      - 8083:3001

  store:
    image: posh3120/maison_lila_store:v0.1
    deploy:
    depends_on:
      - server
      - admin
    ports:
      - 8082:3000

volumes:
  postgres:
